### PR TITLE
bb.fetch: fix mirrors ordering for mirrortarballs

### PR DESCRIPTION
**Pull request by kergoth**
The existing behavior tried all mirrors for tarball one, then all mirrors for
tarball two, whereas we'd be better off trying all tarballs at each mirror
instead, so change bb.fetch to do so.

### CODE REVIEW

**Comment by kergoth** [comment]
This works around the issue encountered in SB-8267.

**Comment by frederiksdun** [comment]
I had same idea this morning.
Currently verifying for cedar.

**Comment by frederiksdun** [comment]
It also works for cedar.

**Comment by kergoth** [comment]
With this, the bitbake selftests start passing again. ping, @Noor-Ahsan

**Pull request merged**
